version: '3.8'

services:
  frontend:
    build: .
    ports:
      - '80:80'
    depends_on:
      - backend

  backend:
    build: ./sudoku-backend
    ports:
      - '3001:3001'
    environment:
      - MONGODB_URI=mongodb://mongo:27017/sudoku
      - PORT=3001
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
